apiVersion: v1
kind: Secret
metadata:
  name: classifier-secrets
type: Opaque
data:
  postgres-user: aGFtemE=
  minio-user: aGFtemE=
  postgres-password: ZnV6enl0ZXN0ZHJhZ29u
  minio-password: ZnV6enl0ZXN0ZHJhZ29u  
